name: Azure login

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Azure login'
      uses: azure/login@v1.4.3
      with:
          creds: ${{ secrets.AZ_CREDS }}
  
