name: Creating VNet bash

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Azure login'
      uses: azure/login@v1.4.3
      with:
          creds: ${{ secrets.AZ_CREDS }}
    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        inlineScript: = |
          chmod +x $GITHUB_WORKSPACE/bash-scripts/vnet.sh
          $GITHUB_WORKSPACE/bash-scripts/vnet.sh Test
        
