name: Creating VNet bash

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Creating VM
      uses: azure/CLI@v1
      with:
        inlineScript: = |
          chmod +x $GITHUB_WORKSPACE/bash-scripts/vm.sh
          $GITHUB_WORKSPACE/bash-scripts/vm.sh
